name: Release
on:
  push:
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0

      - name: Set up NodeJS
        uses: actions/setup-node@v2.5.1
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.UPLOAD_PACKAGES_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
