name: Validate
on:
  pull_request:

jobs:
  build-validate:
    name: "Build (validate)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3.1.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
